### ISSUE TITLE
amqp modul for downloader

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp#38]
Ahoj Jardo,

Pozadavky na sluzbu:
- rychla kontrola na validnost url
- zadost na stazeni obsahu z url
- amqp sluzba ve vlastnim vhost

Protoze se jedna o kontakt se svetem a navic nespolehlivy, myslim, ze toto patri do samostatneho asynchronniho modulu.

A ja doplnim do workflow stav "validace url" a "downloading from url".

**Comment by Bystroushaak** [comment]
Done.
