### ISSUE TITLE
edeposit.amqp does not install pdfgen module

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp#39]
Hi,
rm -rf edeposit
virtualenv --no-site-packages edeposit
cd edeposit
./bin/pip install python-daemon==1.6
./bin/pip install edeposit.amqp
... no module edeposit.amqp.pdfgen installed
./bin/pip install edeposit.amqp.pdfgen
... installation proceeded
... no binary to start pdfgen amqp service

**Comment by Bystroushaak** [comment]
What.

**Comment by jstavel** [comment]
?

**Comment by Bystroushaak** [comment]
Ah, now I see the problem.

**Comment by jstavel** [comment]
This worked:
./bin/pip install python-daemon==1.6
./bin/pip install edeposit.amqp.pdfgen
./bin/pip install edeposit.amqp

:-)

**Comment by Bystroushaak** [comment]
I've just updated the package.

**Comment by Bystroushaak** [comment]
I've frozen `python-daemon` dependency at 1.6 and added new binary to list of binaries.

**Comment by Bystroushaak** [comment]
Okay, it should work now. The current version of `edeposit.amqp` package is `1.7.2`.

**Comment by jstavel** [comment]
It works now. Thanks!
