### ISSUE TITLE
[Errno 6] No such device or address: '/dev/tty'

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp#41]
edeposit-test:/opt/edeposit # tail var/log/alephdaemon-stdout---supervisor-zjHGen.log 
 glob=globals()                # used in deserializer
 File "/usr/lib/python2.7/site-packages/edeposit/amqp/amqpdaemon.py", line 88, in __init__
con_param, queue, out_exch, out_key
File "/usr/lib/python2.7/site-packages/edeposit/amqp/pikadaemon.py", line 37, in __init__
super(PikaDaemon, self).__init__(queue)
File "/usr/lib/python2.7/site-packages/edeposit/amqp/daemonwrapper.py", line 35, in __init__
self.daemon_runner = runner.DaemonRunner(self)
File "/usr/lib/python2.7/site-packages/daemon/runner.py", line 83, in __init__
self.daemon_context.stdout = open(app.stdout_path, 'w+')
IOError: [Errno 6] No such device or address: '/dev/tty'

**Comment by Bystroushaak** [comment]
Snažím se pochopit, kde dochází k chybě, ale budu k tomu potřebovat víc informací.

**Comment by jstavel** [comment]
je to pustene v tmuxu.
Udelal jsem pip install -U edeposit.amqp
v supervisord bezely pustene procesy (ie. zapomnel jsem je vypnout) - ale teoreticky to nemelo vadit.
Tedka bezi alephdaemon v 5.okne.

**Comment by jstavel** [comment]
Ja pujdu s malou do krouzku, takze budu delat offline. Je to cele Tvoje.
Pripravuji metody co nactou zmeny z alephu do edepositu.

**Comment by Bystroushaak** [comment]
Pomalu začínám uvažovat, že bych z toho celý daemonrunner vyhodil a nechal jen možnost, aby to všechno běželo na popředí, co ty na to? Stejně to používáme jen se ``supervisord``.

**Comment by jstavel** [comment]
myslim, ze to nebude vadit.
BTW: nasel jsem clanky, kde supervisord pouzivaji i pro javu a pry neni
jina nahrada (krome jakehosi docker :-)


Dne 25. února 2015 13:48 Bystroushaak <notifications@github.com> napsal(a):

> Pomalu začínám uvažovat, že bych z toho celý daemonrunner vyhodil a nechal
> jen možnost, aby to všechno běželo na popředí, co ty na to? Stejně to
> používáme jen se supervisord.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edeposit/edeposit.amqp/issues/41#issuecomment-75954186>
> .
>



-- 
Jan Stavěl, programátor
Národní knihovna České republiky
Klementinum 190
110 00 Praha 1
tel: 733 230 772

**Comment by Bystroushaak** [comment]
Hm. Teď jsem na to koukal a tohle by si vyžádalo rozsáhlou refactorizaci, tak se do toho radši nebudu pouštět. Jinak pokud updatuješ edeposit.amqp, tak bych radši vše restartoval - všechny ostatní moduly si z toho tahají vnitřnosti a pokud se lehce změní api, tak je to problém.

**Comment by Bystroushaak** [comment]
Zkoušel jsem teď pouštět aleph daemona ručně a to jde v pořádku.

**Comment by jstavel** [comment]
rucne to jde. Ale v supervisoru to nejde.

**Comment by jstavel** [comment]
jdu se podivat.

**Comment by jstavel** [comment]
tak zatim to nejde. Hm.

**Comment by jstavel** [comment]
zkusim zrestartovat celou tmux session.

**Comment by jstavel** [comment]
restart tmuxu nepomohl.

**Comment by Bystroushaak** [comment]
Ajajaj.

**Comment by Bystroushaak** [comment]
Já ani nechápu v čem je přesně ta chyba - jako kdyby to nemohlo získat přístup k /dev/tty. Běží to pod rootem?

**Comment by Bystroushaak** [comment]
Zřejmně to nebude chyba jen u nás:
- LarkIT/newrelic-nfsiostat#7
- LarkIT/newrelic-nfsiostat#16
- armooo/cloudprint#19
- armooo/cloudprint#31
- robmadole/jig#10
- joyjit/git-jira-hook#2

Podle všeho to má dvě řešení - donutit ``supervisord`` dávat scriptům ``tty``, nebo nasměrovat místo ``/dev/tty`` na ``/dev/null``.

**Comment by Bystroushaak** [comment]
Právě jsem releasnul novou verzi, prosím o otestování.

**Comment by jstavel** [comment]
Diky, uz to funguje.

**Comment by Bystroushaak** [comment]
:)
